matrix:
  include:
    - stage: testing
      language: python
      python:
        - "3.6"
      install:
        - pwd
        - ls
        - ls -l reqs
        - pip install reqs/requirements.txt
      script:
        - python -m pytest --no-print-logs src/
